# Generated by Django 4.2.7 on 2025-03-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInfoByExc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('camera_direction', models.IntegerField()),
                ('plate_number', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
